name: Octopy-Energy

channels:
  - conda-forge
  - anaconda-fusion
  - defaults

dependencies:
  # core
  - python=3.7
  - jupyterlab
  - pip
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - twine
  - xarray
  
  # devops/docs
  - python-dotenv
  - mkdocs-material
  - tabulate

  # pip
  - pip:
      - -e .
      - ipypb
      - feautils
      - mkdocs-material-extensions
      - mkdocstrings