site_name: Octopy-Energy
repo_url: https://github.com/AyrtonB/Octopy-Energy
repo_name: AyrtonB/Octopy-Energy

theme:
  name: material
  logo: 'img/logo.png'
  icon:
    #logo: img/logo
    repo: fontawesome/brands/git-alt
  features:
    - header.autohide
    - navigation.tabs
    - navigation.instant
    - search.suggest

extra:
  generator: false
      
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist
  - footnotes
  - attr_list
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  
plugins:
  - search
  - mkdocstrings
  
extra_css:
  - stylesheets/extra.css
      
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
nav:
  - index.md
  - Getting-Started.md
  - API-Layers.md
  - Advanced-Queries.md
